// Build data/homes/<district>.json -- where along each road its homes are --
// from the district's leaflet-map sheet and the OS Open UPRN file. See
// js/homes.js for what the file is for and its format, and README.md
// ("Home positions") for when to rerun it.
//
//   node tools/build-homes.js <sheet> <osopenuprn.csv> <out.json>
//
//   <sheet>  the district's Data sheet: a published-CSV URL, or a CSV file
//   <osopenuprn.csv>  OS Open UPRN (the same file leaflet-pipeline uses,
//            e.g. osopenuprn_202605.csv; free, Open Government Licence)
//   <out.json>  e.g. data/homes/stafford.json
//
// Rerun it whenever the district's sheet is regenerated by the pipeline
// (road geometry changes make old entries stop matching -- safely, but
// those roads lose their positions until it's rerun). Status changes
// (roads marked done) don't need a rerun.
'use strict';
const fs = require('fs');
const path = require('path');
const readline = require('readline');
const Sheets = require('../js/sheets');
const Homes = require('../js/homes');

async function readSheet(src) {
  if (/^https?:/.test(src)) {
    const res = await fetch(src);
    if (!res.ok) throw new Error(`Sheet download failed: HTTP ${res.status}`);
    return res.text();
  }
  return fs.readFileSync(src, 'utf8');
}

async function main() {
  const [sheetSrc, uprnPath, outPath] = process.argv.slice(2);
  if (!sheetSrc || !uprnPath || !outPath) {
    console.error('Usage: node tools/build-homes.js <sheet CSV file or URL> <osopenuprn.csv> <out.json>');
    process.exit(1);
  }

  console.log('Reading sheet…');
  const sheet = Sheets.fromCsvText(await readSheet(sheetSrc));
  const rows = [...sheet.rows, ...sheet.networkRows];
  console.log(`  ${sheet.rows.length} road rows (+${sheet.networkRows.length} network-only)`);

  // Area to keep UPRNs from: every row's geometry, plus a margin wider than the 40 m match radius.
  let latMin = Infinity, latMax = -Infinity, lonMin = Infinity, lonMax = -Infinity;
  for (const r of rows) for (const frag of Homes.fragments(r.roadGeometry)) for (const [lon, lat] of frag) {
    if (lat < latMin) latMin = lat; if (lat > latMax) latMax = lat;
    if (lon < lonMin) lonMin = lon; if (lon > lonMax) lonMax = lon;
  }
  const pad = 0.002;
  latMin -= pad; latMax += pad; lonMin -= pad * 1.6; lonMax += pad * 1.6;

  console.log(`Scanning ${path.basename(uprnPath)} (takes a minute or so)…`);
  const points = [];
  const rl = readline.createInterface({ input: fs.createReadStream(uprnPath), crlfDelay: Infinity });
  let header = null, iLat = -1, iLon = -1, n = 0;
  for await (const line of rl) {
    if (!header) {
      header = line.replace(/^﻿/, '').split(',');
      iLat = header.indexOf('LATITUDE'); iLon = header.indexOf('LONGITUDE');
      if (iLat < 0 || iLon < 0) throw new Error('UPRN file needs LATITUDE and LONGITUDE columns');
      continue;
    }
    n++;
    const cols = line.split(',');
    const lat = +cols[iLat], lon = +cols[iLon];
    if (lat >= latMin && lat <= latMax && lon >= lonMin && lon <= lonMax) points.push([lat, lon]);
  }
  console.log(`  ${n.toLocaleString()} UPRNs read, ${points.length.toLocaleString()} around the district`);

  const { index, stats } = Homes.buildIndex(rows, points, { source: `OS Open UPRN (${path.basename(uprnPath)})` });
  const homesInSheet = sheet.rows.reduce((s, r) => s + r.residences, 0);
  console.log(`  ${stats.afterCommercialFilter.toLocaleString()} after dropping commercial clusters; ` +
    `${stats.placed.toLocaleString()} placed on ${stats.roads} roads (${stats.far.toLocaleString()} of them ${Homes.MATCH_RADIUS_M}-${Homes.FAR_MATCH_M} m away, at their nearest point) ` +
    `(the sheet counts ${homesInSheet.toLocaleString()} homes)`);

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, JSON.stringify(index) + '\n');
  console.log(`Wrote ${outPath} (${Math.round(fs.statSync(outPath).size / 1024)} KB)`);
}

main().catch(e => { console.error(e.message); process.exit(1); });
